#!/bin/sh
#
# name    : vimx
# author  : jKey Lu <jkeylu@gmail.com>
# license : GPL
#

ln -s ~/.vim/vimrc ~/.vimrc
mkdir ~/.vim/bundle
git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
vim +BundleInstall +qall
